name: Release 3.11 wheel

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true

permissions:
  contents: write

jobs:

  release:
    name: Publish release
    runs-on: ubuntu-latest
    steps:

      # see https://github.com/marketplace/actions/download-workflow-artifact
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: local-build.yml
          path: wheels

      - name: List wheels
        run: |
          mkdir dist
          mv wheels/**/*.whl dist
          rm -rf wheels
          ls dist
          
      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: ${{ secrets.PYPI_USERNAME }}
          password: ${{ secrets.PYPI_PASSWORD }}

      # see https://github.com/marketplace/actions/create-release
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.whl"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.tag }}




